### ISSUE TITLE
Allow delta encoding on time.Time

### ISSUE THREAD

**Issue by infogulch** [parquet-go/parquet-go#112]
Currently adding the `delta` tag to a struct field of type `time.Time` panics with: `panic: delta is an invalid parquet tag: time time.Time [delta]`. I would like if delta was allowed on struct fields of type `time.Time.` This could have a big impact on the compressability of timeseries-like data, while allowing users to use language native data types.

Related: #87

**Comment by achille-roussel** [comment]
That sounds like a good feature to add, thanks for making the suggestion @infogulch 👍 

Would you have cycles available to contribute this change to the project?

**Comment by infogulch** [comment]
Sure, I opened a PR that adds support for this struct tag, at least syntactically. Further guidance would be appreciated; details in the PR.
