### ISSUE TITLE
Lazy Reading Large Parquets 

### ISSUE THREAD

**Issue by OtavioHenrique** [parquet-go/parquet-go#124]
Hi Folks, thanks for the amazing project.

I don't know if I missed something on the docs, but there's any way to lazy read parquets on demand, without loading it entirely on memory? (For cases where the parquets does not fit on memory)

I've read [this](https://github.com/parquet-go/parquet-go?tab=readme-ov-file#optimizing-reads) section of README but I don't know if is what I'm looking for.

I would like to somehow stream row by row

Thanks for any help!

**Comment by achille-roussel** [comment]
Hello @OtavioHenrique 

The behavior you describe is the default when you use a parquet reader, you can read rows progressively, underneath the reader takes care of only loading enough data in memory to support decoding the current row. 

Let me know if you've observed a different behavior in your program.

**Comment by OtavioHenrique** [comment]
Hi! Thanks for the answer!

**Comment by OtavioHenrique** [comment]
Hi! Thanks for the answer!
