### ISSUE TITLE
test failed on go tip

### ISSUE THREAD

**Issue by reusee** [parquet-go/parquet-go#138]
```
 go test      
# github.com/parquet-go/parquet-go.test
link: github.com/parquet-go/parquet-go/hashprobe/aeshash: invalid reference to runtime.aeskeysched
FAIL	github.com/parquet-go/parquet-go [build failed]

```

```
| go version  
go version devel go1.23-e3d87d1932 Sat May 18 22:36:41 2024 +0000 linux/amd64

```

**Comment by reusee** [comment]
related: https://github.com/golang/go/issues/67401

**Comment by achille-roussel** [comment]
Thanks for reporting, let's get this fixed!

**Comment by jimyag** [comment]
> ```
>  go test      
> # github.com/parquet-go/parquet-go.test
> link: github.com/parquet-go/parquet-go/hashprobe/aeshash: invalid reference to runtime.aeskeysched
> FAIL	github.com/parquet-go/parquet-go [build failed]
> ```
> 
> ```
> | go version  
> go version devel go1.23-e3d87d1932 Sat May 18 22:36:41 2024 +0000 linux/amd64
> ```

hi @achille-roussel  Can you make a release, [this pr](https://github.com/parquet-go/parquet-go/pull/142) already fixes the above mentioned problem.

![image](https://github.com/parquet-go/parquet-go/assets/69233189/c6d73a48-3f86-443f-b833-cbb9736ece08)

**Comment by achille-roussel** [comment]
Fixed by https://github.com/parquet-go/parquet-go/releases/tag/v0.23.0 !
