### ISSUE TITLE
MergedRowReader overwriting values

### ISSUE THREAD

**Issue by thorfour** [parquet-go/parquet-go#139]
We had a bug report on [FrostDB](https://github.com/polarsignals/frostdb/issues/873) where the merged row reader was returning corrupted rows.

I'm still not wholly certain how it's happening but tracked it down to happening during the `ReadRows` method where values are getting corrupted on subsequent reads.

https://github.com/parquet-go/parquet-go/blob/b3c3a0c3ed6fd14d75c919b6179c64edcc2ee08d/merge.go#L231-L261

This patch fixed the row corruption where we clone each value before copying it into the buffer.

```bash
diff --git a/merge.go b/merge.go
index f100788..778f4e3 100644
--- a/merge.go
+++ b/merge.go
@@ -240,7 +240,10 @@ func (m *mergedRowReader) ReadRows(rows []Row) (n int, err error) {
        for n < len(rows) && len(m.readers) != 0 {
                r := m.readers[0]

-               rows[n] = append(rows[n][:0], r.head()...)
+               rows[n] = rows[n][:0]
+               for _, v := range r.head() {
+                       rows[n] = append(rows[n], v.Clone())
+               }
```

**Comment by thorfour** [comment]
According to this comment in the ReadRows function https://github.com/parquet-go/parquet-go/blob/b3c3a0c3ed6fd14d75c919b6179c64edcc2ee08d/row_group.go#L322-L326 it's not valid to retain values without calling clone first. So I think the correct fix is the above patch.

**Comment by fpetkovski** [comment]
I had the impression this was fixed by https://github.com/parquet-go/parquet-go/pull/31.

I also wonder if we could somehow clone into existing rows to avoid allocating all the time.

**Comment by thorfour** [comment]
So is the recommendation to not use the `ReadRows` api and instead the `WriteRowsTo`?

Seems like quite the footgun
