### ISSUE TITLE
disable min/max page values per column

### ISSUE THREAD

**Issue by derekperkins** [parquet-go/parquet-go#145]
We're writing html files to parquet. Right now, page statistics are being written with the "min" and "max" values, but that isn't useful for a block of multiple megabytes of html, but it does bloat the file size.

There's a similar ticket for Java.
https://issues.apache.org/jira/browse/PARQUET-1911

My thought would be to add a new struct tag option, `nostats`, `nobounds`, `skipbounds` or something like that, and skip the min/max calculations. Would you be opposed to supporting that?

**Comment by derekperkins** [comment]
I added a quick PR to see if I'm approaching this the right way, feel free to let me know if you'd like a different direction, like a  WriterOption

**Comment by derekperkins** [comment]
After that first pass, it seemed like overkill to make it available to readers, so I made a new PR adding a WriterOption that feels a little better. Again, let me know your thoughts on a preferred implementation, or if you even think this should be an option.

**Comment by achille-roussel** [comment]
I left a review on the PR you submitted, the approach sounds good to me 👍
