### ISSUE TITLE
docs: add comparison for Read vs ReadRows

### ISSUE THREAD

**Issue by derekperkins** [parquet-go/parquet-go#149]
What's the difference between `Read` and `ReadRows`, and is there a recommendation to use one over the other? ~They have the same function signature~, `Read` uses a function on the reader, that isn't obvious exactly what it does.

https://github.com/parquet-go/parquet-go/blob/4bc33ce9ea4319989cb104c7f3f5f4a83551711c/reader.go#L106-L119

**Comment by derekperkins** [comment]
My bad, I overlooked that `Read` is generic, while `ReadRows` is not. Is there any reason to choose `ReadRows`?

**Comment by achille-roussel** [comment]
`ReadRows` is a lower-level API, you can skip reconstruction of values into high-level data types. In some cases this is useful to improve performance. It can also be used to perform operations on parquet files when the program doesn't necessarily have a Go data type to represent the rows.

For example, compaction of parquet files is implemented by combining multiple `parquet.RowReader` with [`parquet.MergeRowReaders`](https://pkg.go.dev/github.com/parquet-go/parquet-go#MergeRowReaders).
