### ISSUE TITLE
Can a `*parquet.File` be used from multiple goroutines?

### ISSUE THREAD

**Issue by jhump** [parquet-go/parquet-go#167]
It looks like, as long as the underlying `io.ReaderAt` is thread-safe that a `*parquet.File` is also thread-safe -- since each stateful read operation (that must track state of where the reader's position is) creates a new object. (Those stateful objects are of course _not_ thread-safe.) This appears true of the various readers as well as `ColumnChunk.Pages`.

However, if this is the intent, there is an issue with column and index offsets: when they are lazy-loaded via `ColumnChunk.ColumnIndex` or `ColumnChunk.OffsetIndex`, the chunk will be mutated so the newly loaded data structure can be written to a field.

The above seems rather easy to address by either using atomic pointers for these values or guarding access/update via a mutex. But I wonder if there might be other issues with attempting to re-use a single `File` from multiple goroutines? My use case would prefer to cache the file (and all of the parsed metadata) and then create multiple readers that all want to seek to different points in the file and then stream rows from that point. So I'm just wondering if it this usage is acceptable. (The `io.ReaderAt` implementation I am using is thread-safe.)

If it _is_ intended to be acceptable, and the race conditions around lazy-initializing the indexes in `ColumnChunk` are a bug, ~I'm happy to contribute a fix~ please take a look at pull request 168 😄.

**Comment by fpetkovski** [comment]
This is a good question. When I added the lazy loading of column and offset indices I did not take into account concurrency. 

This makes sense to me, but would like to hear @achille-roussel's opinion on whether the `File` type was meant to be used concurrently.

**Comment by achille-roussel** [comment]
We didn't document that `*parquet.File` should be safe to use concurrently but it's true that it was implicitly safe before we made some internals lazy-load.

Since it's a read-only type, it seems like a good improvement to guarantee concurrency-safety 👍
