### ISSUE TITLE
Speeding up streaming read from remote storages (S3, etc.)

### ISSUE THREAD

**Issue by dolzenko** [parquet-go/parquet-go#188]
First of all big thank you for opensourcing this great project :heart: 

Wanted to get some ideas on how one can read large files without buffering in memory and without significant slow down. I haven't dug into code yet, only had time to do quick test by passing minio.Object to parquet.GenericReader, but performance drop was like 10x compared if I buffer in memory. I assume this makes sense since under the hood there must be many ReadAt happening converted to Range= requests.

**Comment by achille-roussel** [comment]
Hello @dolzenko, thanks for opening an issue!

Have you looked at using [`parquet.FileConfig.ReadMode`](https://pkg.go.dev/github.com/parquet-go/parquet-go#FileConfig.ReadMode) to enable reading pages asynchronously?

Often times, the cause of poor reading performance is the latency of round trips to object storage; by default, parquet-go reads pages sequentially, but it can be useful to read them asynchronously to amortize the cost of those storage operations.

**Comment by dolzenko** [comment]
@achille-roussel all these options look like absolutely what we need. Gotta read the docs next time, big thanks again!

**Comment by stevbear** [comment]
Hi @achille-roussel, I want to quickly follow up on the question above.
It seems like each page will result in a read request to cloud storage. Is there a way that we can read multiple pages in one read request to cloud storage, assuming that the pages are sequential (say, page number 2 to 4)?

**Comment by achille-roussel** [comment]
Hello @stevbear 

Guessing the page sizes to size reads is possible but a bit complex and not reliable, but the simplest path currently would be to change the read buffer size https://pkg.go.dev/github.com/parquet-go/parquet-go#ReadBufferSize, make it a multiple of the estimated average size of compressed pages.

If you control the write path, you cana also control the target size of uncompressed pages via https://pkg.go.dev/github.com/parquet-go/parquet-go#PageBufferSize

Let me know if that answered your questions.

**Comment by stevbear** [comment]
Thanks @achille-roussel . 
So if I use column indexes and page indexes to narrow my target down to a few pages, I can then use Read() and it would buffer up to my specified size?
I assume that it would not work if those pages are not sequential?

**Comment by stevbear** [comment]
Actually, looking at the implementation, it seems to still be reading one page at a time?

**Comment by achille-roussel** [comment]
The read buffer size applies at the I/O level, so if the buffer is large enough it will load the content for multiple pages within a single read from the storage layer (the `io.ReaderAt`).

What I was getting at is that parquet-go isn't trying to be smart here, even if the page index exists, it doesn't try to guess the best next buffer size to load pages, it simply reads pages from storage using ` bufio.Reader` sized on the configured read buffer size.
