### ISSUE TITLE
versioned 0.x.x releases

### ISSUE THREAD

**Issue by gernest** [parquet-go/parquet-go#19]
There is a note on the README that we are on `0.x.x` and things are subject to change. A new home needs a new start. One of the things I would like to do is start tagging our releases.

I intentionally didn't break things on #16  relating to renaming `GenericReader`  to  `Reader[T]` for this reason. No need to break things without a clear migration path.

The plan is  to 

-  After consolidating current work I will make the first release `0.x.x`
-  I will remove all deprecated features and embrace generics, possibly move requirements to `go1.20` then increment the `minor` component of the semver and drop  a new release (which will be the way forward for the package development).

This way , users can pin to specific tags, and we can always back port bug fixes. 

_**note:**_

I haven't  decided on which tag version to start with (`v0.1.0` sounds silly lol!) , any suggestions are welcome.

**Comment by kevinburkesegment** [comment]
Why not v1.0? It sounds like a lot of people are using this in production? Otherwise yeah maybe let's just pick a higher number, v0.17 or something, why not.

**Comment by gernest** [comment]
see https://github.com/parquet-go/parquet-go/releases/tag/v0.17.0
