### ISSUE TITLE
Optimistically reading file footer breaks Tempo caching logic

### ISSUE THREAD

**Issue by joe-elliott** [parquet-go/parquet-go#193]
I like [this recent PR](https://github.com/parquet-go/parquet-go/pull/192) and believe it will help in the general case, but Tempo has logic to [immediately return the footer length and cache the footer](https://github.com/grafana/tempo/blob/e61733554c09fb59d6990eff48dc9c511b5c22cf/tempodb/encoding/vparquet4/readers.go#L98-L114) in an off process cache. This PR breaks that behavior by changing the ranges it attempts to read.

Are we good on a PR to make this new behavior configurable? I'd be glad to submit it.

**Comment by achille-roussel** [comment]
Thanks for chiming in!

OK, let me revert it first and let's think more about it 👍

**Comment by achille-roussel** [comment]
I opened #195, I think I'm satisfied with this approach, let me know if you have any concerns.

**Comment by joe-elliott** [comment]
Thanks Achille!
