### ISSUE TITLE
Support field IDs in parquet schemas

### ISSUE THREAD

**Issue by gernest** [parquet-go/parquet-go#20]
See  https://github.com/segmentio/parquet-go/issues/156

**Comment by tongwai-wong-appier** [comment]
Thank you guys for this great feature.

For nested types (e.g., map/array), the _inner_ element can also specify an id.
(e.g. element id for array element, key id/value id for map element).

I noticed that for map type, this can be done by **parquet-key**/**parquet-value** tag

```go
type TestFieldId struct {
	Iamamap   map[string]string `parquet:",id(1)" parquet-key:",id(2)" parquet-value:",id(3)"`
}
```

How can I add an element id for an array type in parquet-go?
