### ISSUE TITLE
Write Parquet file with custom schema

### ISSUE THREAD

**Issue by workanator** [parquet-go/parquet-go#25]
Hello,

is that possible to produce parquet files whose schema is not known at compile time? I'm trying like in the example below but getting NULL in all fields in each row.

```go
package main

import (
	"os"

	"github.com/parquet-go/parquet-go"
)

func main() {
	file, err := os.Create("test.parquet")
	if err != nil {
		panic(err)
	}
	defer file.Close()

	s := parquet.NewSchema("Record", parquet.Group{
		"Text": parquet.Optional(parquet.String()),
	})
	w := parquet.NewGenericWriter[any](file, s)
	_, err = w.WriteRows([]parquet.Row{{
		parquet.ByteArrayValue([]byte("Hello")),
	}})
	if err != nil {
		panic(err)
	}

	err = w.Close()
	if err != nil {
		panic(err)
	}
}
```

The schema generated is
```
Metadata for file: test.parquet

version: 1
num of rows: 1
created by: github.com/parquet-go/parquet-go version 0.0.0(build bb12c19a1110)
metadata:
message Record {
  OPTIONAL BYTE_ARRAY Text (STRING);
}
```

And when I output content of the produced file
```
#################################################
File: test.parquet
#################################################

{Text: null}
```

**Comment by gernest** [comment]
Hey @workanator ,

It is possible but you will be using deprecated API .  You also uncovered a bug , unfortunate it is on the deprecated API so I won't be fixing it .

You can use something like this 

```go
	file, err := os.Create("test.parquet")
	if err != nil {
		panic(err)
	}
	defer file.Close()

	s := parquet.NewSchema("Record", parquet.Group{
		"Text": parquet.String(),
	})
	conf, err := parquet.NewWriterConfig()
	if err != nil {
		t.Fatal(err)
	}
	conf.Schema = s
	w := parquet.NewWriter(file, conf)
	if err != nil {
		panic(err)
	}
	_, err = w.WriteRows([]parquet.Row{
		{
			parquet.ValueOf("hello"),
		},
	})
	if err != nil {
		t.Fatal(err)
	}
	err = w.Close()
	if err != nil {
		t.Fatal(err)
	}
```

Note that I removed `parquet.Optional` from the field. For some reason `WriteRows` writes incorrect data when the fields are optional , I checked it with other data types as well.

I recommend you use `GenericWriter`.

**Comment by workanator** [comment]
Thank you @gernest!

I confirm that works but all NULLs (`parquet.NullValue()`) converted into zero values. :(

I would like to use a typed `GenericWriter`, that is a cool feature and I love it, but unfortunately in my project input schema is unknown, it varies with almost each input file, so I have to compose the output schema on the fly.

**Comment by gernest** [comment]
You are welcome. I'm closing this , please feel free to reopen if I didn't properly answer your question.

**Comment by workanator** [comment]
You answered my question Geofrey. Thank you! Though I still need to write optional values. Maybe you can give me a clue where I can start digging for the bug which does not allow writing optional values when GenericWriter is not used?
