### ISSUE TITLE
RLE encoding cannot be specified in parquet struct tags

### ISSUE THREAD

**Issue by zolstein** [parquet-go/parquet-go#29]
When generating a schema for a type, there's no struct tag value to specify regular RLE encoding. It seems like all this requires is an additional case when checking the tags and an update to the documentation.

I'm happy to submit a PR for this if it's as simple as it seems.

**Comment by gernest** [comment]
> I'm happy to submit a PR for this if it's as simple as it seems.

Go for it.

A PR actually gives me a better view on the scope of the ticket. We can always move the discussion between the issue and the PR.

**Comment by zolstein** [comment]
In trying to learn a bit more about this, I read the [Parquet Encodings documentation](https://parquet.apache.org/docs/file-format/data-pages/encodings/) more thoroughly, which says:

> Note that the RLE encoding method is only supported for the following types of data:
Repetition and definition levels
Dictionary indices
Boolean values in data pages, as an alternative to PLAIN encoding

So on further inspection it doesn't make sense to add this.
