### ISSUE TITLE
I'm sorry

### ISSUE THREAD

**Issue by gernest** [parquet-go/parquet-go#36]
Based on https://github.com/parquet-go/parquet-go/issues/1 , I had the wrong impression I was the only one who stepped up and temporary taking over maintaining this project.

Fixing issues and ensuring the healthy of the library has been my core objective. I raised a ticket to outline first steps I had in mind for the project here https://github.com/parquet-go/parquet-go/issues/19.

Unfortunately, I was operating under the assumption I can make correct judgement while executing my duties. I had no impression that there are other maintainers out there who were actively involved for this I'm terribly sorry.

I love this project and I want it to thrive,  If my actions hurts the project in any way I apologise to anyone affected by it.

For those who were wondering.

I merged a fix to a critical issue https://github.com/parquet-go/parquet-go/pull/31 without giving time for maintainers to review.

That being said, I have some questions.

- Is there governance for this project that I'm not aware of ?
- Is there a list of active maintainers ?
- Should I step down ?
- What should be done moving forward ? I'm happy to revert  all non approved changes, Including removing the release just please let me know who I should talk to.

Thanks and  have a good day.

**Comment by kevinburkesegment** [comment]
I don't think you should apologize. Personally I would rather bias towards doing things than bias towards waiting for a consensus that might not arrive. I really appreciate all of your energy towards improving the project.

**Comment by fpetkovski** [comment]
I concur, you have done an amazing job so far and there is no need for apologies. I do wonder if we want a list of current and previous maintainers though for some basic visibility.

**Comment by joe-elliott** [comment]
I appreciate your enthusiasm, but agree we should slow things down. There are a number of very large projects that depend on this library and we should be thoughful about changes.

> Is there governance for this project that I'm not aware of ?
> Is there a list of active maintainers ?

Not that I'm aware of, but I think we need it.

> Should I step down ?

No. 

> What should be done moving forward ? I'm happy to revert all non approved changes, Including removing the release just please let me know who I should talk to.

All changes should require approval. We should definitely not be merging things that have not been code reviewed. We should setup a CODEOWNERS file so you can easily ping us for a review. 

I am personally fine with the release, but we should have more coordination and awareness of cutting releases.

**Comment by mdisibio** [comment]
> All changes should require approval. We should definitely not be merging things that have not been code reviewed. We should setup a CODEOWNERS file so you can easily ping us for a review.

I'd like to also get together a basic roadmap.  No strong preferences on how or what form, could be a section in the readme, GH discussion, etc.  The recent changes are all great and agreeable (go version, cleanup, etc), but need consensus before deprecating APIs or more impactful changes.

**Comment by gernest** [comment]
Seeing the feedback here its pretty clear to me the project is still alive and in good hands. 

I paid close attention to this because I thought it was abandoned, I didn't want my favourite package to die.

I was committing to this between interviews,  I think Its best for me to focus more on my preps . I'm very happy to see all these people who are more capable than me chiming in. I see people from @grafana and @polarsignals

With that being said, **I am officially stepping down as a maintainer** .  I don't mind my permissions being taken away.
