### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by kevinburkesegment** [parquet-go/parquet-go#4]
Attempting to get the tests passing to merge a rewrite references change, I get the following error:

```
FAIL: TestOpenFile (2.01s)
    --- FAIL: TestOpenFile/testdata/issue368.parquet (0.00s)
        file_test.go:38: reading parquet file metadata: decoding thrift payload: -10:FIELD<?>: skipping unsupported thrift type 15
FAIL
FAIL	github.com/parquet-go/parquet-go	39.395s
ok  	github.com/parquet-go/parquet-go/bloom	0.02[7](https://github.com/parquet-go/parquet-go/actions/runs/5534777733/jobs/10100177839#step:5:8)s
ok  	github.com/par
```

**Comment by kevinburkesegment** [comment]
Either testdata/issue368.parquet was encoded by a different library than segmentio/encoding, or we are decoding the fields incorrectly to get an unknown 15th field.

**Comment by kevinburkesegment** [comment]
Ah, I can't reproduce this with GO111MODULE=on so I think this is a dependency version issue.

**Comment by kevinburkesegment** [comment]
@gernest - if you are looking for ways to help out, taking a look at this would be really helpful!

**Comment by gernest** [comment]
Yeah,  Before I merge my PR Fixing CI is the priority  for now. I think we can remove old Go versions from the matrix. The library is heavy on generics as it is right now. Supporting current stable go versions should be priority practical choice)

My hunch it might be the case for this issue.

running 

```

 make test
```

locally seems to pass for me.

**Comment by gernest** [comment]
confirmed the test failure. Will now investigate.

**Comment by gernest** [comment]
Interesting, this test has been falling since forever. Did a quick bisect and came up with what  commit that introduced this issue.

https://github.com/segmentio/parquet-go/pull/484
