### ISSUE TITLE
Problems with dynamic schemas and writing with optional fields

### ISSUE THREAD

**Issue by KasonBraley** [parquet-go/parquet-go#42]
I am new to this package, and have a requirement for building dynamic schema's at runtime, but am having problems getting the whole solution to work. I have seen many other issues regarding this, but have been unable to piece together a full solution. Most the other issues are either unanswered, or don't have a full code snippet that works. As part of this, I am also needing Optional fields.

These are all the similar issues I have read and have not been able to figure it out.

- https://github.com/parquet-go/parquet-go/issues/30
- https://github.com/segmentio/parquet-go/issues/311
- https://github.com/parquet-go/parquet-go/issues/25
- https://github.com/segmentio/parquet-go/issues/392
- https://github.com/segmentio/parquet-go/issues/310
---

I would like to create a schema at runtime. Both of these two options appear to work correctly for me when I create the schema.

```go
schema := parquet.NewSchema("runtime_schema", parquet.Group{
	"id":  parquet.Optional(parquet.Int(32)),
	"age": parquet.Optional(parquet.Int(32)),
})
```

```go
structFields := []reflect.StructField{}

tp := reflect.TypeOf(int32(0))

structFields = append(structFields, reflect.StructField{
	Name: strings.ToUpper("age"),
	Type: tp,
	Tag:  reflect.StructTag(fmt.Sprintf(`parquet:"%v,optional"`, "age")),
})
structFields = append(structFields, reflect.StructField{
	Name: strings.ToUpper("id"),
	Type: tp,
	Tag:  reflect.StructTag(fmt.Sprintf(`parquet:"%v,optional"`, "id")),
})

structType := reflect.StructOf(structFields)
structElem := reflect.New(structType)

schema := parquet.NewSchema("runtime_schema", parquet.SchemaOf(structElem.Interface()))
```

Both of those options create the same schema as expected:
```
message runtime_schema {
        optional int32 age (INT(32,true));
        optional int32 id (INT(32,true));
}
```

I am not sure on which option is better? I have seen both ways suggested in different issues: https://github.com/parquet-go/parquet-go/issues/30#issuecomment-1649189264, https://github.com/segmentio/parquet-go/issues/311#issuecomment-1219031236.

Now, the problem I am running in to, is using the the `GenericWriter` with this schema. I am unsure of what to put for the type parameter, so I have been using `any`. It compiles, and effectively "works", but nothing I have tries works with Optional fields.

When trying to use `WriteRows` with optional fields, in any way the schema is defined(typed struct, `Group`, or reflection), the optional fields are always null. This bug was noted here:https://github.com/parquet-go/parquet-go/issues/25#issuecomment-1642459872, although the comment made it seem like it was only on the deprecated `Writer` api, however it appears to also apply to the `GenericWriter` as well. Example of the bug with `GenericWriter`: https://github.com/parquet-go/parquet-go/issues/30#issuecomment-1656347829.

Now, I don't have a specific need for `WriteRows` right now, but it's the only way I could get it to compile, or not panic when writing. When trying to use [`Write`](https://pkg.go.dev/github.com/segmentio/parquet-go#GenericWriter.Write) instead, I run into panics. Usually of some reflection call. I'm sure I'm just making a simple mistake.

I am able to use `Write` like this:
```go
func main() {
	schema := parquet.NewSchema("runtime_schema", parquet.Group{
		"id":  parquet.Optional(parquet.Int(32)),
		"age": parquet.Optional(parquet.Int(32)),
	})

	var f bytes.Buffer
	pw := parquet.NewGenericWriter[any](&f, schema)

	a := []any{
		map[string]int32{
			"id":  20,
			"age": 22,
		},
	}

	_, err := pw.Write(a)
	if err != nil {
		log.Fatal(err)
	}
	if err := pw.Close(); err != nil {
		log.Fatal(err)
	}

	reader := parquet.NewGenericReader[any](bytes.NewReader(f.Bytes()), schema)
	out := make([]parquet.Row, 1)
	if _, err := reader.ReadRows(out); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%+v", out)
}
```

Prints: `[[C:0 D:1 R:0 V:22 C:1 D:1 R:0 V:20]]`                    

however this very simplified schema will not work for my use case. Because the schema isn't just of one type. So I would need to use a `map[string]any`, but it panics.

Example:
```go
func main() {
	schema := parquet.NewSchema("runtime_schema", parquet.Group{
		"id":   parquet.Optional(parquet.Int(32)),
		"age":  parquet.Optional(parquet.Int(32)),
		"name": parquet.Optional(parquet.String()),
	})

	var f bytes.Buffer
	pw := parquet.NewGenericWriter[any](&f, schema)

	a := []any{
		map[string]any{
			"id":   20,
			"age":  22,
			"name": "bob",
		},
	}

	_, err := pw.Write(a)
	if err != nil {
		log.Fatal(err)
	}
	if err := pw.Close(); err != nil {
		log.Fatal(err)
	}

	reader := parquet.NewGenericReader[any](bytes.NewReader(f.Bytes()), schema)
	out := make([]parquet.Row, 1)
	if _, err := reader.ReadRows(out); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%+v", out)
}
```

This panics with:
```
panic: cannot create parquet value of type INT32 from go value of type interface {}

goroutine 1 [running]:
github.com/parquet-go/parquet-go.makeValue(0x1, 0xc00018a930, {0x796100?, 0xc0000254a0?, 0xc000193a60?})
        /home/kason/go/pkg/mod/github.com/parquet-go/parquet-go@v0.17.0/value.go:339 +0xd89
github.com/parquet-go/parquet-go.deconstructFuncOfLeaf.func1({0xc00009c3c0, 0x3, 0xc0000a7410?}, {0xd0?, 0x71?, 0x41?}, {0x796100?, 0xc0000254a0?, 0x198?})
        /home/kason/go/pkg/mod/github.com/parquet-go/parquet-go@v0.17.0/row.go:538 +0x99
github.com/parquet-go/parquet-go.deconstructFuncOfOptional.func1({0xc00009c3c0?, 0x3?, 0x3?}, {0x0?, 0x0?, 0x0?}, {0x796100?, 0xc0000254a0?, 0xc000193bd0?})
        /home/kason/go/pkg/mod/github.com/parquet-go/parquet-go@v0.17.0/row.go:439 +0x103
github.com/parquet-go/parquet-go.deconstructFuncOfGroup.func1({0xc00009c3c0, 0x3, 0x3}, {0xc0?, 0x3b?, 0x19?}, {0x79d840?, 0xc0000a7410?, 0x7fb0e0?})
        /home/kason/go/pkg/mod/github.com/parquet-go/parquet-go@v0.17.0/row.go:515 +0x19c
github.com/parquet-go/parquet-go.(*Schema).deconstructValueToColumns(0xc000092300, {0xc00009c3c0, 0x3, 0x3}, {0x79d840?, 0xc0000a7410?, 0x7a8400?})
        /home/kason/go/pkg/mod/github.com/parquet-go/parquet-go@v0.17.0/schema.go:236 +0x114
github.com/parquet-go/parquet-go.(*Schema).Deconstruct(0xc000092300, {0x0, 0x0, 0x0}, {0x79d840?, 0xc0000a7410})
        /home/kason/go/pkg/mod/github.com/parquet-go/parquet-go@v0.17.0/schema.go:224 +0x1f4
github.com/parquet-go/parquet-go.(*Writer).Write(0xc0000925a0, {0x79d840, 0xc0000a7410})
        /home/kason/go/pkg/mod/github.com/parquet-go/parquet-go@v0.17.0/writer.go:379 +0x1d6
github.com/parquet-go/parquet-go.(*GenericWriter[...]).writeAny(0x0, {0xc000025490?, 0x1, 0x10})
        /home/kason/go/pkg/mod/github.com/parquet-go/parquet-go@v0.17.0/writer.go:233 +0x65
github.com/parquet-go/parquet-go.(*GenericWriter[...]).Write.func1(0xc000193e30?)
        /home/kason/go/pkg/mod/github.com/parquet-go/parquet-go@v0.17.0/writer.go:169 +0x62
github.com/parquet-go/parquet-go.(*writer).writeRows(0xc000188160, 0x1, 0xc000193e28)
        /home/kason/go/pkg/mod/github.com/parquet-go/parquet-go@v0.17.0/writer.go:993 +0xbb
github.com/parquet-go/parquet-go.(*GenericWriter[...]).Write(0xc0000a7410?, {0xc000025490?, 0x4?, 0xc0000686b0?})
        /home/kason/go/pkg/mod/github.com/parquet-go/parquet-go@v0.17.0/writer.go:168 +0x65
main.main()
        /home/kason/nuspire/nusiem-log-mover/cmd/parquet2/main.go:36 +0x4cd
exit status 2
```

Any help would be greatly appreciated! Thank you.

**Comment by KasonBraley** [comment]
So I've been able to finally get the `Write` method to work correctly, even with Optional fields in the schema. Using the schema struct built with reflection, and then building up the struct instance allowed it work.

```go
func main() {
	structFields := []reflect.StructField{}

	structFields = append(structFields, reflect.StructField{
		Name: strings.ToUpper("name"),
		Type: reflect.TypeOf(""),
		Tag:  reflect.StructTag(fmt.Sprintf(`parquet:"%v,optional"`, "name")),
	})
	structFields = append(structFields, reflect.StructField{
		Name: strings.ToUpper("id"),
		Type: reflect.TypeOf(int32(0)),
		Tag:  reflect.StructTag(fmt.Sprintf(`parquet:"%v,optional"`, "id")),
	})
	structFields = append(structFields, reflect.StructField{
		Name: strings.ToUpper("age"),
		Type: reflect.TypeOf(int32(0)),
		Tag:  reflect.StructTag(fmt.Sprintf(`parquet:"%v,optional"`, "age")),
	})

	structType := reflect.StructOf(structFields)
	structElem := reflect.New(structType)

	schema := parquet.NewSchema("runtime_schema", parquet.SchemaOf(structElem.Interface()))

	structValue := structElem.Elem()
	structValue.FieldByName("NAME").Set(reflect.ValueOf("bob"))
	structValue.FieldByName("ID").Set(reflect.ValueOf(int32(7)))
	structValue.FieldByName("AGE").Set(reflect.ValueOf(int32(30)))

	var f bytes.Buffer
	pw := parquet.NewGenericWriter[any](&f, schema)

	a := []any{
		structValue.Interface(),
	}

	_, err := pw.Write(a)
	if err != nil {
		log.Fatal(err)
	}
	if err := pw.Close(); err != nil {
		log.Fatal(err)
	}

	reader := parquet.NewGenericReader[any](bytes.NewReader(f.Bytes()), schema)
	out := make([]parquet.Row, 1)
	if _, err := reader.ReadRows(out); err != nil {
		log.Fatal(err)
	}
	fmt.Printf("%+v", out)
}
```

This correctly prints: `[[C:0 D:1 R:0 V:bob C:1 D:1 R:0 V:7 C:2 D:1 R:0 V:30]]`.

And then if I comment out the `ID` field for example, it prints that field as null as I would expect: `[[C:0 D:1 R:0 V:bob C:1 D:0 R:0 V:<null> C:2 D:1 R:0 V:30]]`

So I may have answered my own problems. I am just wondering if there is possibly a better/more efficient way to achieve this? In practice l will be ranging over column names gathered from elsewhere to build up this struct, so it'll be more involved then this simple example. Also the bug in `WriteRows` still exists, although I don't think I need it now.

**Comment by curio77** [comment]
There's another issue that currently stumps me.  That problem is that when writing 0-values to optional columns, they become null-values.

This can be reproduced by setting `ID` to 0 instead of 7 in the above example.  This also happens with other column types, e.g., `float64`.
