### ISSUE TITLE
set the compression algorithm when using NewGenericWriter?

### ISSUE THREAD

**Issue by flo8** [parquet-go/parquet-go#49]
I am currently using [xitongsys Parquet library ](https://github.com/xitongsys/parquet-go)and wanted to give this one a try to compare the performance.

Is there a way to set the compression algorithm when using NewGenericWriter? I have been reading the doc and quickstart but couldn't find any example on how to do this or if it is even possible?

**Comment by achille-roussel** [comment]
parquet-go does support setting a default compression algorithm on writers as well https://pkg.go.dev/github.com/segmentio/parquet-go#Compression

With this option, compression defaults to the configured codec for columns that had no compression explicitly set in their schema.
