### ISSUE TITLE
[PowerBI] Yet implemented: Unsupported encoding.

### ISSUE THREAD

**Issue by ocordeiro** [parquet-go/parquet-go#50]
I encountered an error while attempting to open a file with a string column in PowerBI. The specific error message I received was:

```Parquet: class parquet::ParquetException (message: 'Not yet implemented: Unsupported encoding.')```

Interestingly, the issue does not occur when the Parquet file contains only numeric columns; it works perfectly in that case.

However, I successfully converted data.csv, which contains strings, to Parquet format using parquet-tools, and I was able to open it in PowerBI without any problems.

Here is the code I used to test the scenario:

```go
// Not works
type RowString struct{ Data string }
parquet.WriteFile("file_with_string.parquet", []RowString{
	{Data: "Bob"},
})

// Not works
group := parquet.Group{
	"Data": parquet.Optional(parquet.String()),
}
schema := parquet.NewSchema("schema", group)
output, _ := os.OpenFile("file_with_string2.parquet", os.O_RDWR|os.O_CREATE, 0755)
pw := parquet.NewGenericWriter[any](output, schema)
defer pw.Close()
builder := parquet.NewRowBuilder(group)
builder.Add(0, parquet.ByteArrayValue([]byte(`Bob`)))
pw.WriteRows([]parquet.Row{builder.Row()})

// Works
type RowInt struct{ Data int }
parquet.WriteFile("file_with_int.parquet", []RowInt{
	{Data: 1},
})
```

**Comment by ocordeiro** [comment]
$ parquet meta file_with_string2.parquet
```
Row group 0:  count: 1  38,00 B records  start: 4  total(compressed): 38 B total(uncompressed):38 B 
--------------------------------------------------------------------------------
      type      encodings count     avg size   nulls   min / max
Data  BINARY    _         1         38,00 B            "Bob" / "Bob"
```

**Comment by ocordeiro** [comment]
$ parquet meta data.parquet // Converted using parquet-tools (works)

Row group 0:  count: 1  54,00 B records  start: 4  total(compressed): 54 B total(uncompressed):36 B 
--------------------------------------------------------------------------------
      type      encodings count     avg size   nulls   min / max
data  BINARY    G   _     1         54,00 B    0       "Bob" / "Bob"

**Comment by ocordeiro** [comment]
Solved setting encoding to PLAIN:

```parquet.Encoded(parquet.Optional(parquet.String()), &parquet.Plain)```

**Comment by crodwell** [comment]
Same problem with loading Parquet files to ClickHouse. Strings are default encoded with 
`encodings: DELTA_LENGTH_BYTE_ARRAY` and this is not yet supported: https://github.com/ClickHouse/ClickHouse/issues/44505

**Comment by achille-roussel** [comment]
Thanks for highlighting that issue with clickhouse. 

Delta length encoding is defined as the default for strings in the parquet spec, and it seems that there is intent to address the issue on the clickhouse side, so I wouldn't recommend to change behavior here, especially considering we don't know what other issues it might cause to programs that depend on the current behavior.
