### ISSUE TITLE
Data corruption when recording byte array column statistics

### ISSUE THREAD

**Issue by zolstein** [parquet-go/parquet-go#53]
Discovered while implementing https://github.com/parquet-go/parquet-go/pull/52

parquet-cli showed that for one of the sample columns containing ["Solo", "Skywalker", "Skywalker"] the min and max values recorded were ("Skywalker", "Skywalker"), not ("Skywalker", "Solo") as they should have been.

I spent a bit more time investigating this. The problem comes from these lines in (*writerColumn).recordPageStats [(writer.go:1560)](https://github.com/parquet-go/parquet-go/blob/1e4f8bbc561c9ea189f4557efd7b056a6a021277/writer.go#L1560): 

```golang
if existingMaxValue.isNull() || c.columnType.Compare(maxValue, existingMaxValue) > 0 {
    c.columnChunk.MetaData.Statistics.MaxValue = maxValue.Bytes()
}
```

For byte-array-backed Values, [Bytes()](https://github.com/parquet-go/parquet-go/blob/1e4f8bbc561c9ea189f4557efd7b056a6a021277/value.go#L582) returns an unsafe cast of the value ptr to a byte-slice. In this case, the ptr points into the values slice of the columnBuffer's page, and that slice gets saved directly into the statistics. It seems like after we finish flushing this page, the page's values slice gets reused - as the next page is written, it overwrites the MaxValue stored in the statistics. In this particular case, the stored MaxValue _was_ "Solo" (&values[0], 4) but "Skywalker" is the first value of the next data page, which gets written to &values[0]. When we update the statistics for this page, we compare "Skywalker" (&values[0], 9) against "Skyw" (&values[0], 4), find it's larger, and updates it. In general, though, this could behave even more erratically.

Fundamentally, it seems like the solution is that the stored value needs to be copied into a slice backed by a new array, not left pointing to the one inside the page. The question is: how should we do it?

Option 1: Change the implementation of (Value).Bytes() to always copy the bytes into a new array. This makes the API less dangerous and may prevent other bugs like this, but it will negatively impact performance anywhere Bytes() is called and creating a copy is not dangerous. It's hard to assess how big a deal this is from either perspective. Bytes() is currently only called in (*writerColumn).makePageStatistics and (*writerColumn).recordPageStats. We have to add the copy in recordPageStats, but makePageStatistics _seems_ to work as-is (I think this is because this value isn't held past the page flush in this case.) However, because Value is exported outside the package, the level of safety and performance impact is probably overwhelmed by the effects on usage outside the package, which are hard to know. I worry a little bit that from outside the package it's nearly impossible to tell when the value returned by Bytes is safe or when it needs to be copied, unless for some reason all values exposed outside the module are safe.

Option 2: We could do the copy inside (*writerColumn).recordPageStats. This has the smallest impact on the system, affecting only the one site where we know there's a problem. However, it leaves us and others open to similar bugs in the future. ~It also imposes a small performance/complexity hit on recordPageStats, though in practice this probably won't matter much.~ EDIT: I realized that using (Value).AppendBytes actually works better than (Value).Bytes in all cases, and requires the fewest unnecessary allocations.

Option 3: Implement a new method (Value).SafeBytes() (name TBD) that always copies the data into a new slice, and let the caller decide on the behavior. IMO this probably pollutes the API more than it provides useful options, but I include it for completeness.

**Comment by zolstein** [comment]
A little bit more investigation shows this is probably regressed with this PR: https://github.com/segmentio/parquet-go/pull/508. Prior to this, (Value).Bytes() always copied into a new array. However, this PR changed it to return the underlying bytes directly to improve performance. I couldn't find any reference to the specific benchmark that justified it, but my guess is the person who made that commit (and others processing lots of data as raw values?) would object to functionally reverting that change, so maybe we ought to just fix it inside recordPageStats?

I wonder, though, what are the guarantees about the stability of values that bubble up outside of the reader? Are Values returned by ReadRows guaranteed to remain valid once they're returned? Are they valid until the next call? Can they become corrupted even before they're returned if, say, a read crosses a page boundary? If the second, this should probably be documented. If the third, this should be fixed.

**Comment by zolstein** [comment]
I opened a PR to fix this issue, using a version of Option 2. I modified recordPageStats to use (Value).AppendBytes, which seems like the best way to do the copy we need without doing extraneous copies and mallocs. https://github.com/parquet-go/parquet-go/pull/54

**Comment by achille-roussel** [comment]
> I wonder, though, what are the guarantees about the stability of values that bubble up outside of the reader?
> Are Values returned by ReadRows guaranteed to remain valid once they're returned?
> Are they valid until the next call?

The expectations are documented on the `parquet.RowReader` interface https://pkg.go.dev/github.com/parquet-go/parquet-go#RowReader

> Can they become corrupted even before they're returned if, say, a read crosses a page boundary?

They cannot become corrupted at page boundaries, parquet-go is implemented to gracefully handle those conditions. Technically, what we do is leverage the fact that `ReadRows` or `ReadValues` are allowed to return fewer items than the size of the slice they receive as argument, even when no errors occurred (same semantic as `io.Reader`). When we reach the end of a page, we _early return_ to the caller so the internal buffers contain the values from only one page, and they can be reused when reading the following page.

**Comment by zolstein** [comment]
PR is merged, so I'm closing this.
