### ISSUE TITLE
Sorting for nested structure column

### ISSUE THREAD

**Issue by dewy01** [parquet-go/parquet-go#59]
Hey, i have a problem with sorting parquet file by nested column.
For example look at these structs

type Data struct {
    ID string
    Time   int64
    Values Value
}

type Value struct {
    Freq  float64
    Power float64
}

The string of column name looks like "Values.Freq"

When i try to use
parquet.Ascending("Values.Freq")
It doesnt work. 

Is there any other way to sort parquet file by nested value?

**Comment by zolstein** [comment]
From the look of it, you should do parquet.Ascending("Values", "Freq"). 
```
// Ascending constructs a SortingColumn value which dictates to sort the column
// at the path given as argument in ascending order.
func Ascending(path ...string) SortingColumn { return ascending(path) }
```

**Comment by dewy01** [comment]
For anyone struggling with the same issue, this works perfectly fine
