### ISSUE TITLE
Merging row groups throws panic when rows from one group are empty

### ISSUE THREAD

**Issue by fpetkovski** [parquet-go/parquet-go#66]
Merging multiple sorted row groups will throw a panic when one of the groups returns empty rows during `ReadRows`, even if `n` is correctly returned as 0. The reason why we sometimes return empty rows is because we apply filtering during the merge process, and occasionally no rows will match the filter. I think this only happens when the entire row group is empty.

Here is a PR reproducing the issue: https://github.com/parquet-go/parquet-go/pull/67.

**Comment by fpetkovski** [comment]
The bug is only present when using the `WriteRowsTo` method because it uses the newly introduced mergeBuffer: https://github.com/parquet-go/parquet-go/blob/0205873edb71c7175cb4abb8f136e574e7a5cdae/merge.go#L111-L118.

Not a long term solution, but temporarily I was able to move forward by wrapping merge row groups in a new struct that looks like this, which basically strips that method:

```
type rowGroupReaderOnly struct {
	parquet.RowGroup
}

func (r rowGroupReaderOnly) Rows() parquet.Rows {
	return readRowsOnly{r.RowGroup.Rows()}
}

type readRowsOnly struct {
	parquet.Rows
}
```

**Comment by gernest** [comment]
@fpetkovski I might be late, did you share the stack trace of the panic somewhere ?

**Comment by fpetkovski** [comment]
Hey @gernest, there is one stacktrace here https://github.com/parquet-go/parquet-go/pull/61#issuecomment-1721517007.

**Comment by gernest** [comment]
Am I correct to say that the stack trace you linked is for this issue but the comment is on a thread that is not directly related to this issue ?

I just don't want to confuse things.    For context , there is a reason why we have `WriteRowsTo`. And Indeed this panic looks interesting  but I'm seeing `/go/pkg/mod/github.com/zolstein/segio-parquet-`  on the stack trace.  I assume this doens't  reflect how you came across the issue it contains unrelated changes.

So, I can't run your repro yet, If you don't mind can you re run the repro on  based on current master branch and  share the stack trace with me ?

**Comment by gernest** [comment]
gentle ping @fpetkovski

**Comment by fpetkovski** [comment]
Sorry @gernest, I missed your last message. I rebased my branch on latest main and ran the test again. Here is the stack trace from the panic, let me know if this helps:

```
--- FAIL: TestMergeRowGroups (0.01s)
    --- FAIL: TestMergeRowGroups/buffer (0.00s)
        --- FAIL: TestMergeRowGroups/buffer/reproduce_issue_#66,_merging_rows_with_an_empty_row_group (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0

goroutine 25 [running]:
testing.tRunner.func1.2({0x177c800, 0xc0000280c0})
	/usr/local/go/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1399 +0x39f
panic({0x177c800, 0xc0000280c0})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/parquet-go/parquet-go.(*mergeBuffer).read(0xc0022b0000)
	/Users/filippetkovski/Projects/parquet-go/merge.go:463 +0x1ba
github.com/parquet-go/parquet-go.(*mergeBuffer).WriteRowsTo(0xc0022b0000, {0x18d3820, 0xc000515b90})
	/Users/filippetkovski/Projects/parquet-go/merge.go:434 +0x6b
github.com/parquet-go/parquet-go.(*mergedRowGroupRows).WriteRowsTo(0xc000513380, {0x18d3820, 0xc000515b90})
	/Users/filippetkovski/Projects/parquet-go/merge.go:114 +0x1ca
github.com/parquet-go/parquet-go.copyRows({0x18d3820, 0xc000515b90}, {0x276a320, 0xc000513380}, {0x0, 0x0, 0x0})
	/Users/filippetkovski/Projects/parquet-go/row.go:319 +0x3d5
github.com/parquet-go/parquet-go.CopyRows(...)
	/Users/filippetkovski/Projects/parquet-go/row.go:293
github.com/parquet-go/parquet-go_test.copyRowsAndClose({0x18d3820?, 0xc000515b90?}, {0x18df770?, 0xc000513380?})
	/Users/filippetkovski/Projects/parquet-go/parquet_test.go:992 +0xc5
github.com/parquet-go/parquet-go_test.TestMergeRowGroups.func1.1(0xc0004b8ea0)
	/Users/filippetkovski/Projects/parquet-go/merge_test.go:345 +0x505
testing.tRunner(0xc0004b8ea0, 0xc00050eca8)
	/usr/local/go/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:1493 +0x35f
```

**Comment by gernest** [comment]
@fpetkovski thanks, I think I have an idea to address this.

I am preparing a patch  to fix this. Will ping you when its ready.
