### ISSUE TITLE
Allow opening a single RowGroup

### ISSUE THREAD

**Issue by fpetkovski** [parquet-go/parquet-go#83]
The `OpenFile` function parses the page index of all row groups, which for large files (100GB+) can already take a couple of seconds. It would be great to have an API which allows the user to open a set of row groups instead opening all of them.

**Comment by achille-roussel** [comment]
Hello @fpetkovski, thanks for opening this discussion!

I agree this improvement would be useful; maybe an alternative would be to figure out how to lazily parse the page index when it is first accessed instead of on open, so the application only pays for what it uses. What do you think?

**Comment by fpetkovski** [comment]
That would work great as well 👍 

In addition to the lazy processing, most queries can easily be easily parallelized between row groups. So by using multiple cores we would make the overhead of opening a file go away.
