### ISSUE TITLE
Add support to int16

### ISSUE THREAD

**Issue by gcmanriq** [parquet-go/parquet-go#93]
When trying to write an int16 field 

panic: cannot convert Go values of type int16 to parquet value
goroutine 6 [running]:
github.com/parquet-go/parquet-go.writeRowsFuncOf({0x100cfa8c8, 0x100884200}, 0x0?, {0xc000614600, 0x1, 0x1})
        /Users/c12326a/git/credit-header/ch-build-conmaster/vendor/github.com/parquet-go/parquet-go/column_buffer.go:2016 +0x588

**Comment by achille-roussel** [comment]
Hello @gcmanriq, thanks for starting this discussion!

We're tracking this change as part of https://github.com/parquet-go/parquet-go/issues/121 already, so I'll close this issue but feel free to follow up on the other one.
